worker_processes auto;

events { }

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    upstream strapi_upstream {
        server strapi-app:1337;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://strapi_upstream;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /uploads/ {
            proxy_pass http://strapi_upstream/uploads/;
        }

        client_max_body_size 20M;
    }
}
