name: CD - Terraform Deploy

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Docker image tag to deploy"
        required: true
        default: latest

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-north-1

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve \
          -var="key_name=${{ secrets.EC2_KEY_NAME }}" \
          -var="image_name=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-north-1.amazonaws.com/paktha-my-strapi-repo-1" \
          -var="image_tag=${{ github.event.inputs.image_tag }}" \
          -var="app_keys=${{ secrets.APP_KEYS }}" \
          -var="api_token_salt=${{ secrets.API_TOKEN_SALT }}" \
          -var="admin_jwt_secret=${{ secrets.ADMIN_JWT_SECRET }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-north-1
